services:
  mongo:
    image: mongo:latest
    container_name: to-do-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: to-do-app-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoDB 

volumes:
  mongo-data:
